### ISSUE TITLE
Server down? 

### ISSUE THREAD

**Issue by HugoGresse** [pumbaa666/discord_bot#12]
Coucou,

J'ai bien ajouté le bot sur mon discord, mais à chaque commande discord affichde "L'application ne répond plus"

**Comment by pumbaa666** [comment]
My bad, je n'avais pas relancé le serveur après ma dernière session de test.
C'est tout bon maintenant ! :ok_hand:

**Comment by HugoGresse** [comment]
Wouhou !! c'est top et ça marche bien ! 
Il manque plus que un Uptime (upptime ou updown.io) :D

**Comment by pumbaa666** [comment]
je n'avais pas pensé à un uptime.
J'ajoute ça aux TODO's.

Content que le bot te plaise.
N'hésite pas à donner des retours.
